### ISSUE TITLE
BHC doesn't keep its settings (ubuntu 24.10 gnome 47 Wayland)

### ISSUE THREAD

**Issue by nicolastaffin** [maniacx/Battery-Health-Charging#116] opened 2024-11-08 20:23 UTC
Lenovo yoga slim 6, ubuntu 24.10 gnome 47 Wayland

Thanks first for you work !

BHC works a bit, but it is sometimes there, sometimes not,
widget is sometimes highlighted, sometimes not, 
sometimes on max capacity, sometimes back to max lifespan. 
I can't understand the pattern. 

Also : when i click on max capacity, notifies a "failed setting" error then goes back to previous setting.

Not sure how to provide more information, but i'd be happy to if useful.

**Comment by maniacx** [comment] 2024-11-08 23:46
I apologize,  I am aware of the issue. However I cannot solve it.
The issue is that pkexec command when executed from gnome-extension, delays by 120 seconds.
This only affect Ubuntu and debian based systems running wayland and polkit 124 or above.
It works well in Xorg though in debian and Ubuntu system.

I have been trying for week to know, find out what is the issue.
I have reached out to gnome-extension matrix channel, raise and issue with polkit and also ubuntu forums. 
So far nobody has an idea, what is going on.

Fedora wayland or Xorg doesnt have this issue. I only found the issue in Debian and ubuntu and assuming the issue will be present for debian/ubuntu based distro.

https://github.com/polkit-org/polkit/issues/510#issuecomment-2451387828

Thank you for reporting.

Can you trying logging in Xorg once just only to confirm if it works.
And report back to me.

**Comment by nicolastaffin** [comment] 2024-11-09 08:13
Hi @maniacx you don't need to apologize (especially if you can't solve this)
So if i understand it's a delay, and we don't need an immediate battery policy, so despite it's a bit confusing on the feedback side, it should work.
I tested under X11 and it is reacting to my changes yes. However, in x11 also, the control widget is sometimes highlited, sometimes not, and i'm not sure what it  means

What is the difference between 

![Capture d’écran du 2024-11-09 09-10-11](https://github.com/user-attachments/assets/50ee9215-0e4f-4479-88de-29524c59b1b1)
and
![Capture d’écran du 2024-11-09 09-09-59](https://github.com/user-attachments/assets/14c410f3-ef4a-4d43-80a2-65b5c3d75753) 

It looks like i'm on / i'm off but not sure.
changing the policy in the menu, makes the widget go off. And often back to max lifespan policy.
Then, minutes later, it seems to be always off, but with the requested policy.

**Comment by nicolastaffin** [comment] 2024-11-09 08:16
If i get your point, the workaround (for now) is
- request what you want
- ignore any widget feedback (text and color) (the notification seems to be OK anyway)
- wait 120 s
- check later if you are good

is it ?

**Comment by maniacx** [comment] 2024-11-10 20:42
Let me have a look if anything else is changed with ubuntu.

**Comment by petr-fischer** [comment] 2024-11-20 13:18
Same behaviour here (also ubuntu 24.10 gnome 47 Wayland) - every click (settings change) on the "widget" in the Gnome quick settings lasts cca 120 seconds, but also, it eats one CPU core for 100% the whole 120 seconds.
Current solution is - don't click on the widget like a maniac.

If you want some debug logging etc. I am ready.

**Comment by maniacx** [comment] 2024-11-20 14:25
I have tried everything. I am not sure. This only happens in ubuntu and Debian base system that uses wayland. Unfortunately, I do not know how to proceed further, but just wait till polkit team or ububtu forums respond, but there no response from them either.

**Comment by nicolastaffin** [comment] 2024-11-20 14:55
OK let's wait & see… It more or less works this way, meanwhile. Thanks

**Comment by petr-fischer** [comment] 2024-11-24 15:40
Also, next feedback: after going from the "screen blank/screensaver" state (screen blank activated with the `xdg-screensaver activate`), two `pkexec... CHEKINSTALLATION` were started
![Screenshot From 2024-11-24 16-29-04](https://github.com/user-attachments/assets/46d815b7-15ef-4eb0-b5ed-c7d9ed6ca11d)

**Comment by maniacx** [comment] 2024-11-25 00:32
That happens when the extension is rebasing. 
When any extension is enable, it will enable and disable other extension. 
That is how gnome-extension works. So when laptop wake up from sleep state extension get repeatadly disable and enabled. earlier it was not noticable as pkexec executes instantly.

But due the the 120s delay in wayland. Now it is noticable. Only way I can avoid it is by using a delay execution of pkexec.
I think, I should work this out on the next release by adding a 1 second delay.

**Comment by maniacx** [comment] 2024-12-21 08:35
@petr-fischer 
@nicolastaffin 


I have created a script to use `sudo`  to be used as a workaround as I cannot solve the bugs with `polkit`. We can continue, our testing and discussion on this thread.

https://github.com/maniacx/Battery-Health-Charging/issues/122

I will close this issue.

**Closed as completed by maniacx** 2024-12-21 08:35 UTC
